# Generated by Django 2.2.28 on 2023-02-19 10:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('experienced', models.BooleanField()),
                ('conflicts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('technical', models.BooleanField()),
                ('nontechnical', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='JudgingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('judges', models.ManyToManyField(blank=True, related_name='judging_room', to='judging.Judge')),
                ('teams', models.ManyToManyField(blank=True, related_name='judging_room', to='judging.Team')),
            ],
        ),
        migrations.CreateModel(
            name='AwardNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('announcement', models.CharField(max_length=5000)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judging.Award')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judging.Team')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='callback_teams',
            field=models.ManyToManyField(blank=True, related_name='callback_teams', to='judging.Team'),
        ),
        migrations.AddField(
            model_name='award',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judging_panel', to='judging.Judge'),
        ),
        migrations.AddField(
            model_name='award',
            name='nominated_teams',
            field=models.ManyToManyField(blank=True, related_name='nominated_teams', to='judging.Team'),
        ),
    ]
